// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVCu1ksj4O4N-ZPsq4lcYqr4InivwiFx8',
    appId: '1:964152886946:web:992248790c0cbde2ec39fb',
    messagingSenderId: '964152886946',
    projectId: 'fir-instgram-ui',
    authDomain: 'fir-instgram-ui.firebaseapp.com',
    storageBucket: 'fir-instgram-ui.appspot.com',
    measurementId: 'G-2Q0GGKL2QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiF5alvt9jSgQEPJcd_PCgftTVyjkpDnM',
    appId: '1:964152886946:android:9e8da4d75488574aec39fb',
    messagingSenderId: '964152886946',
    projectId: 'fir-instgram-ui',
    storageBucket: 'fir-instgram-ui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn27GSitr0u1OUSwJcfx1KHYjw5V5rdHE',
    appId: '1:964152886946:ios:81cb264c4599dbcfec39fb',
    messagingSenderId: '964152886946',
    projectId: 'fir-instgram-ui',
    storageBucket: 'fir-instgram-ui.appspot.com',
    iosClientId: '964152886946-p9238088fbac7s98ko523j3una8tfekv.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.instagramFirebaseUi',
  );
}
